CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_I2C=y
CONFIG_GPIO=y
# Если это MCP23017:
CONFIG_GPIO_PCA95XX=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_USE_CHOSEN_LAYOUT=y
